### ISSUE TITLE
Stone allowed to be placed in a suicide position

### ISSUE THREAD

**Issue by poplav** [brilee/go_implementation#2]
@brilee , I was testing out the `go_naive.py` implementation and ran into a case that I am confused about and was hoping you can clarify.
Example suppose I configure an 9 by 9 board and run the following sequence:
```
pos = Position.initial_state()
pos = pos.play_move(0, 'O')
pos = pos.play_move(1, 'X')
pos = pos.play_move(9, 'X')
pos = pos.play_move(0, 'O')
```
As expected after the third move `X` kills `O` and captures the position.  But then on the fourth move I am allowed to place the `O` back into the 0th position.  I would have thought this fourth move would throw an illegal move exception or such, right or am I missing something?  Additionally I note the score changes from 81 to 79 from the third to fourth move respectively.

FYI, I am new to the game of Go, so please excuse me

**Comment by brilee** [comment]
Yep, it's a bug - I'm not checking for suicides in this implementation. Shame on me. I'll push a fix in a sec.

**Comment by brilee** [comment]
see commit https://github.com/brilee/go_implementation/commit/96d08345fdc4f45da61b7bf63beba1f192889273

**Comment by poplav** [comment]
Thanks, confirmed it looks to fix/resolve the issue
